name: ci

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup bazelisk for Bazel builds
        uses: holvonix-open/setup-bazelisk@v0.5.1
      - run: echo $PWD
      - run: ls -al
      - run: which bazelisk bazel
      - run: export
      - run: bazelisk
      - run: bazel --version
      - run: bazelisk --version
      - run: echo 3.1.0 > .bazelversion
      - run: bazelisk
      - run: bazel --version
      - run: bazelisk --version
