name: ci

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    setps:
      - name: Setup bazelisk for Bazel builds
        uses: holvonix-open/setup-bazelisk@v0.1.0
      - run: bazel --version
      - run: bazelisk --version
      - run: echo 3.1.0 > .bazelversion
      - run: bazel --version
      - run: bazelisk --version
